# Generated by Django 5.0.6 on 2026-07-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_default_zones"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryzone",
            name="is_external",
            field=models.BooleanField(
                default=False,
                help_text="Стоимость по API перевозчика; порог бесплатной доставки не применяется.",
                verbose_name="Внешний перевозчик (СДЭК)",
            ),
        ),
    ]
