# Generated by Django 5.0.6 on 2026-07-20 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_adr444_zones"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                ("starts_at", models.TimeField(verbose_name="Начало интервала")),
                ("ends_at", models.TimeField(verbose_name="Конец интервала")),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("courier", "Курьерская доставка"), ("pickup", "Самовывоз")],
                        default="courier",
                        max_length=20,
                        verbose_name="Способ доставки",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Лимит заказов",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — слот доступен во всех зонах.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="delivery.deliveryzone",
                        verbose_name="Зона доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот доставки",
                "verbose_name_plural": "Слоты доставки",
                "ordering": ["date", "starts_at"],
                "indexes": [
                    models.Index(fields=["is_active", "date"], name="slot_active_date_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="deliveryslot",
            constraint=models.UniqueConstraint(
                fields=("date", "starts_at", "ends_at", "delivery_method", "zone"),
                name="uniq_delivery_slot_window",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryslot",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="delivery_slot_ends_after_starts",
            ),
        ),
    ]
