# Generated by Django 5.0.6 on 2026-06-20 20:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_product_catalog_product_attrs_gin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Для гостевой корзины (анонимный пользователь).",
                        max_length=40,
                        verbose_name="Ключ сессии",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("ordered", "Оформлена в заказ")],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Оформлена"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Количество")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                        verbose_name="Корзина",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка корзины",
                "verbose_name_plural": "Строки корзины",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(
                        help_text="Человекочитаемый уникальный номер, генерируется при оформлении.",
                        max_length=32,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "external_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Заполняется 1С при выгрузке (sync_1c_status=exported). В #26 пуст.",
                        max_length=64,
                        null=True,
                        verbose_name="Номер заказа в 1С",
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("confirmed", "Подтверждён"),
                            ("assembling", "Собирается"),
                            ("ready", "Готов к выдаче"),
                            ("shipped", "В доставке"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("expired", "Просрочена оплата"),
                            ("refunded", "Возврат"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "sync_1c_status",
                    models.CharField(
                        choices=[("pending", "Ожидает выгрузки"), ("exported", "Выгружен в 1С")],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="Статус выгрузки в 1С",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ФИО / контактное лицо"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("b2c", "Физическое лицо (B2C)"),
                            ("b2b", "Юридическое лицо / ИП (B2B)"),
                        ],
                        default="b2c",
                        max_length=3,
                        verbose_name="Тип покупателя",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название организации"
                    ),
                ),
                ("inn", models.CharField(blank=True, max_length=12, verbose_name="ИНН")),
                ("kpp", models.CharField(blank=True, max_length=9, verbose_name="КПП")),
                (
                    "legal_address",
                    models.CharField(blank=True, max_length=512, verbose_name="Юридический адрес"),
                ),
                (
                    "delivery_method",
                    models.CharField(blank=True, max_length=64, verbose_name="Способ доставки"),
                ),
                (
                    "delivery_address",
                    models.CharField(blank=True, max_length=512, verbose_name="Адрес доставки"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий к заказу")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Заглушка-выбор (без онлайн-оплаты в #26).",
                        max_length=32,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Сумма line_total всех строк.",
                        max_digits=14,
                        verbose_name="Сумма заказа",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "reserved_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Задел под механику резерва (#8). В #26 всегда пуст.",
                        null=True,
                        verbose_name="Резерв до",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="null — гостевой заказ. SET_NULL: заказ переживает удаление пользователя.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_1c", models.CharField(blank=True, max_length=50, verbose_name="Код 1С")),
                ("article", models.CharField(blank=True, max_length=100, verbose_name="Артикул")),
                ("name", models.CharField(max_length=512, verbose_name="Название")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="Единица измерения"),
                ),
                (
                    "price_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "price_final",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Итоговая цена"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(blank=True, max_length=16, verbose_name="Тип цены"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="price_final * quantity.",
                        max_digits=14,
                        verbose_name="Сумма строки",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка заказа",
                "verbose_name_plural": "Строки заказа",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active"), ("user__isnull", False)),
                fields=("user",),
                name="uniq_active_cart_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active"), ("user__isnull", True)),
                fields=("session_key",),
                name="uniq_active_cart_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="uniq_cart_product"
            ),
        ),
    ]
