# Generated by Django 5.0.6 on 2026-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="exported_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Момент первого подтверждения приёма заказа в 1С (sync_1c_status=exported).",
                null=True,
                verbose_name="Дата выгрузки в 1С",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="external_order_number",
            field=models.CharField(
                blank=True,
                help_text="Человекочитаемый номер документа 1С, напр. УТ-000987.",
                max_length=64,
                verbose_name="Номер документа 1С",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=128, verbose_name="Трек-номер доставки"),
        ),
        migrations.AlterField(
            model_name="order",
            name="external_order_id",
            field=models.CharField(
                blank=True,
                help_text="Стабильный технический идентификатор документа 1С (onec_order_id).",
                max_length=64,
                null=True,
                verbose_name="ID заказа в 1С",
            ),
        ),
    ]
