# Generated by Django 5.0.6 on 2026-07-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_moderationproduct"),
        ("orders", "0003_order_access_token"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="uniq_cart_product",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата мягкого удаления"),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Удалена (soft)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="access_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Для доступа к заказу без логина (гостевое оформление).",
                max_length=64,
                verbose_name="Токен гостевого доступа",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("cart", "product"),
                name="uniq_cart_product_active",
            ),
        ),
    ]
