# Generated by Django 5.0.6 on 2026-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_normalize_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reservation_status",
            field=models.CharField(
                choices=[
                    ("none", "Без резерва"),
                    ("held", "Удержан"),
                    ("released", "Возвращён"),
                    ("confirmed", "Списан"),
                ],
                db_index=True,
                default="none",
                help_text="NONE — резерв не создавался; HELD — удержан; RELEASED — возвращён в свободный остаток; CONFIRMED — списан (оплата/подтверждение 1С).",
                max_length=12,
                verbose_name="Статус резерва",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reserved_until",
            field=models.DateTimeField(
                blank=True,
                help_text="TTL резерва: после этого момента janitor освобождает неоплаченный резерв.",
                null=True,
                verbose_name="Резерв до",
            ),
        ),
    ]
