# Generated by Django 5.0.6 on 2026-07-02 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_reservation_status_alter_order_reserved_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_without_vat",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Сумма без НДС",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Сумма НДС"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_rate",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ставка НДС, %"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сумма line_total всех строк (с НДС).",
                max_digits=14,
                verbose_name="Сумма заказа",
            ),
        ),
    ]
