# Generated by Django 5.0.6 on 2026-07-02 19:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_amount_without_vat_order_vat_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_calc_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Не требуется"),
                    ("calculated", "Рассчитана"),
                    ("manual_required", "Ручной расчёт"),
                ],
                db_index=True,
                default="not_required",
                max_length=16,
                verbose_name="Статус расчёта доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="null = стоимость ещё не определена (ручной расчёт менеджером).",
                max_digits=12,
                null=True,
                verbose_name="Стоимость доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="Снимок тарифа доставки"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_zone",
            field=models.CharField(blank=True, max_length=100, verbose_name="Зона доставки (slug)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Товары + доставка, с НДС. При manual_required — предварительный (только товары).",
                max_digits=14,
                verbose_name="Сумма заказа",
            ),
        ),
    ]
