# Generated by Django 5.0.6 on 2026-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_delivery_calc_status_order_delivery_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("expired", "Просрочена оплата"),
                    ("partially_refunded", "Частичный возврат"),
                    ("refunded", "Возврат"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
