# Generated by Django 5.0.6 on 2026-07-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(max_length=40, unique=True, verbose_name="Номер счёта"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Выставлен"),
                            ("paid", "Оплачен"),
                            ("expired", "Истёк"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("issued_at", models.DateTimeField(verbose_name="Выставлен")),
                (
                    "valid_until",
                    models.DateTimeField(
                        db_index=True,
                        help_text="24 часа с момента выставления; совпадает с TTL резерва товара.",
                        verbose_name="Действителен до",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Оплачен")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_invoice",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счёт B2B",
                "verbose_name_plural": "Счета B2B",
                "ordering": ["-issued_at"],
            },
        ),
    ]
