# Generated by Django 5.0.6 on 2026-07-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_deliveryslot_deliveryslot_uniq_delivery_slot_window_and_more"),
        ("orders", "0010_b2binvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="delivery.deliveryslot",
                verbose_name="Слот доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_slot_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="slot_id, date, starts_at, ends_at, delivery_method, zone.",
                verbose_name="Снимок слота доставки",
            ),
        ),
    ]
