# Generated by Django 5.0.6 on 2026-07-20 20:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_delivery_slot_order_delivery_slot_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="promo_code",
            field=models.CharField(blank=True, default="", max_length=40, verbose_name="Промокод"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Скидка на доставку",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items_discount_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Скидка на товары",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.CharField(blank=True, default="", max_length=40, verbose_name="Промокод"),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="Снимок промо"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="promo_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Скидка по акции",
            ),
        ),
    ]
