# Generated by Django 5.0.6 on 2026-08-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_cart_promo_code_order_delivery_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Онлайн-оплата"),
                    ("invoice", "Счёт для организации"),
                    ("cash", "Наличными при получении"),
                    ("card_on_pickup", "Картой при получении"),
                ],
                help_text="Чем оплачен заказ. Набор доступных способов считает available_payment_methods().",
                max_length=32,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
