# Generated by Django 5.0.6 on 2026-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_payment_method_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда заказ перешёл в «Выполнен». От этой даты считается 14-дневный срок заявки на возврат денег.",
                null=True,
                verbose_name="Выполнен в",
            ),
        ),
    ]
