# Generated by Django 5.0.6 on 2026-09-24 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("vkid", "VK ID"), ("yandex", "Яндекс ID")],
                        max_length=16,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(max_length=64, verbose_name="ID у провайдера"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail от провайдера"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя от провайдера"),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True, verbose_name="Привязан")),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последний вход"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привязка VK ID / Яндекс ID",
                "verbose_name_plural": "Привязки VK ID / Яндекс ID",
            },
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="integration_oauth_unique_provider_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="integration_oauth_unique_user_provider"
            ),
        ),
    ]
