# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_chat_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Идентификатор чата в MAX для уведомлений.",
                null=True,
                unique=True,
                verbose_name="MAX chat ID",
            ),
        ),
    ]
