# Generated by Django 5.0.6 on 2026-07-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_phone_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
