# Generated by Django 5.0.6 on 2026-06-20 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=100, verbose_name="Источник")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="Теги")),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль клиента",
                "verbose_name_plural": "Профили клиентов",
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("registration", "Регистрация"),
                            ("order", "Заказ"),
                            ("call", "Звонок"),
                            ("message", "Сообщение"),
                            ("note", "Заметка"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("summary", models.CharField(max_length=500, verbose_name="Описание")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Метаданные")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm_clients.clientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Взаимодействие",
                "verbose_name_plural": "Взаимодействия",
                "ordering": ["-created_at"],
            },
        ),
    ]
