# Generated by Django 5.0.6 on 2026-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, unique=True, verbose_name="Slug")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="meta title"),
                ),
                ("meta_description", models.TextField(blank=True, verbose_name="meta description")),
                ("excerpt", models.TextField(blank=True, verbose_name="Анонс")),
                ("body", models.TextField(blank=True, verbose_name="Содержимое")),
                (
                    "cover",
                    models.ImageField(blank=True, upload_to="articles/", verbose_name="Обложка"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("image", models.ImageField(upload_to="banners/", verbose_name="Изображение")),
                ("link", models.CharField(blank=True, max_length=500, verbose_name="Ссылка")),
                ("alt", models.CharField(blank=True, max_length=255, verbose_name="Alt-текст")),
                (
                    "target",
                    models.CharField(
                        choices=[("home", "Главная"), ("catalog", "Каталог"), ("all", "Везде")],
                        db_index=True,
                        default="home",
                        max_length=20,
                        verbose_name="Цель размещения",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, unique=True, verbose_name="Slug")),
                ("title", models.CharField(max_length=255, verbose_name="Название акции")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="promotions/", verbose_name="Баннер акции"
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="Конец")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-starts_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SEOPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="meta title"),
                ),
                ("meta_description", models.TextField(blank=True, verbose_name="meta description")),
                ("body", models.TextField(blank=True, verbose_name="Содержимое")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO-страница",
                "verbose_name_plural": "SEO-страницы",
                "ordering": ["slug"],
            },
        ),
    ]
