# Generated by Django 5.0.6 on 2026-07-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ["-starts_at", "-created_at"],
                "verbose_name": "Страница акции",
                "verbose_name_plural": "Страницы акций (без скидок)",
            },
        ),
    ]
