# Generated by Django 5.0.6 on 2026-07-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_alter_category_options_and_more"),
        ("content", "0002_alter_promotion_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="catalog_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Блок «подобрать по теме» под статьёй.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="catalog.category",
                verbose_name="Раздел каталога",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="figure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Без схемы"),
                    ("sds-shank", "Хвостовик SDS"),
                    ("battery-storage", "Хранение аккумуляторов"),
                    ("torque-scale", "Шкала момента"),
                    ("disc-marking", "Маркировка дисков"),
                    ("duty-cycle", "Режим работы ПВ"),
                    ("bur-wear", "Износ бура"),
                ],
                default="",
                max_length=32,
                verbose_name="Схема-иллюстрация",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reading_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 — посчитать автоматически по объёму текста.",
                verbose_name="Время чтения, мин",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Выжимка над текстом: по одному пункту на строку, обычно три.",
                verbose_name="Коротко",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="Подпись-ярлык: «Перфораторы».",
                max_length=64,
                verbose_name="Раздел",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="«## » — заголовок раздела, «- » — пункт списка, «> » — врезка, строка из «|» — таблица (первая строка = шапка). Остальное — абзацы.",
                verbose_name="Содержимое",
            ),
        ),
    ]
