# Generated by Django 5.0.6 on 2026-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_article_catalog_category_article_figure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seopage",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="Разметка страницы. «## Заголовок» начинает раздел, следующая строка «:тип» задаёт его вид: :герой, :карточки, :шаги, :чеклист, :вопросы, :контакты, :карта, :теги. В карточках, шагах и вопросах пункт списка делится на две части знаком «|»: «- Самовывоз | Заберите заказ на складе». Строки «изображение:», «кнопка:», «телефон:», «почта:», «режим:», «адрес:», «бейдж:» в начале раздела задают картинку, кнопки и контакты. Остальное — обычный текст: абзацы, «- » списки, «> » врезка, «|» таблица.",
                verbose_name="Содержимое",
            ),
        ),
    ]
