# Generated by Django 5.0.6 on 2026-06-17 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="Профессионал", max_length=200, verbose_name="Название магазина"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="branding/", verbose_name="Логотип"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#00A14B",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", message="Цвет должен быть в формате #RRGGBB"
                            )
                        ],
                        verbose_name="Основной цвет",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#B5E61D",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", message="Цвет должен быть в формате #RRGGBB"
                            )
                        ],
                        verbose_name="Акцентный цвет",
                    ),
                ),
                ("contacts", models.JSONField(blank=True, default=dict, verbose_name="Контакты")),
                (
                    "requisites",
                    models.JSONField(blank=True, default=dict, verbose_name="Реквизиты"),
                ),
                (
                    "region",
                    models.CharField(default="Пенза", max_length=100, verbose_name="Регион"),
                ),
                ("reviews_enabled", models.BooleanField(default=False, verbose_name="Отзывы")),
                ("b2b_enabled", models.BooleanField(default=True, verbose_name="B2B-кабинет")),
                ("promotions_enabled", models.BooleanField(default=False, verbose_name="Акции")),
                (
                    "articles_enabled",
                    models.BooleanField(default=False, verbose_name="Статьи/новости"),
                ),
                ("max_chat_enabled", models.BooleanField(default=False, verbose_name="MAX-чат")),
                (
                    "ai_assist_enabled",
                    models.BooleanField(default=False, verbose_name="AI-консультант"),
                ),
                (
                    "video_reviews_enabled",
                    models.BooleanField(default=False, verbose_name="Видеообзоры"),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
