# Generated by Django 5.0.6 on 2026-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="requisites",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Реквизиты поставщика для счетов B2B. Ключи: company_name, inn, kpp, ogrn, address, phone, bank_name, bank_bik, bank_account, bank_corr_account, director, accountant. Без банковских полей счёт нельзя оплатить — покупателю не из чего заполнить платёжное поручение.",
                verbose_name="Реквизиты",
            ),
        ),
    ]
