# Generated by Django 5.0.6 on 2026-06-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0012_groupcategorymapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("price_request", "Запрос цены"),
                            ("restock_notify", "Уведомить о поступлении"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("name", models.CharField(blank=True, max_length=120, verbose_name="Имя")),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новая"), ("processed", "Обработана")],
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiries",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка по товару",
                "verbose_name_plural": "Заявки по товарам",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status", "kind"], name="leads_produ_status_501aa7_idx")
                ],
            },
        ),
    ]
