# Generated by Django 5.0.6 on 2026-06-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_groupcategorymapping"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinquiry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("price_request", "Запрос цены"),
                    ("restock_notify", "Уведомить о поступлении"),
                    ("consultation", "Консультация"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="productinquiry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inquiries",
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
    ]
