# Generated by Django 5.0.6 on 2026-07-20 19:57

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0026_catalogchange_applied_by_catalogchange_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Активна"),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="Окончание")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процент"),
                            ("fixed_amount", "Фиксированная сумма"),
                            ("free_delivery", "Бесплатная доставка"),
                        ],
                        max_length=16,
                        verbose_name="Тип выгоды",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Процент (1–100) или сумма в валюте корзины; для бесплатной доставки — 0.",
                        max_digits=14,
                        verbose_name="Размер",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("product", "Товары"),
                            ("category", "Категории"),
                            ("cart", "Корзина"),
                        ],
                        max_length=10,
                        verbose_name="Область",
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Пусто — акция автоматическая; иначе применяется только по коду.",
                        max_length=40,
                        verbose_name="Промокод",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Тай-брейк при равной выгоде на строку: больше — важнее.",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Действует на всё поддерево выбранных категорий.",
                        related_name="promotions",
                        to="catalog.category",
                        verbose_name="Категории",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promotions",
                        to="catalog.product",
                        verbose_name="Товары",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("promo_code"),
                condition=models.Q(("promo_code", ""), _negated=True),
                name="uniq_promotion_code_ci",
            ),
        ),
    ]
