# Generated by Django 5.0.6 on 2026-07-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Скидка / промокод",
                "verbose_name_plural": "Скидки и промокоды",
            },
        ),
    ]
