# Generated by Django 5.0.6 on 2026-06-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_exported_at_order_external_order_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "yookassa_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="ID платежа ЮKassa",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("yookassa", "ЮKassa (карта/СБП)"),
                            ("invoice", "Счёт (B2B)"),
                            ("cash", "При получении"),
                        ],
                        default="yookassa",
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("waiting_for_capture", "Ожидает подтверждения"),
                            ("succeeded", "Оплачен"),
                            ("canceled", "Отменён"),
                            ("refunded", "Возвращён"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Сумма"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                ("confirmation_url", models.URLField(blank=True, verbose_name="URL оплаты")),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "webhook_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Последний webhook payload"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата оплаты"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
    ]
