# Generated by Django 5.0.6 on 2026-07-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("waiting_for_capture", "Ожидает подтверждения"),
                    ("succeeded", "Оплачен"),
                    ("canceled", "Отменён"),
                    ("partially_refunded", "Частично возвращён"),
                    ("refunded", "Возвращён"),
                ],
                default="pending",
                max_length=24,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Сумма возврата"
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В обработке"),
                            ("succeeded", "Выполнен"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "yookassa_refund_id",
                    models.CharField(blank=True, max_length=64, verbose_name="ID возврата ЮKassa"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Ключ идемпотентности"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="Платёж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возврат",
                "verbose_name_plural": "Возвраты",
                "ordering": ["-created_at"],
            },
        ),
    ]
