# Generated by Django 5.0.6 on 2026-09-17 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_completed_at"),
        ("payments", "0003_payment_provider_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("changed_mind", "Передумал покупать"),
                            ("defect", "Брак или неисправность"),
                            ("wrong_item", "Привезли не тот товар"),
                            ("incomplete", "Неполная комплектация"),
                            ("delay", "Задержка доставки"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Комментарий покупателя"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("processing", "Оформляется возврат"),
                            ("refunded", "Деньги возвращены"),
                            ("rejected", "Отклонена"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "decision_comment",
                    models.TextField(
                        blank=True,
                        help_text="Покупатель видит этот текст в личном кабинете.",
                        verbose_name="Ответ покупателю",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Когда решено"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто решил",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="payments.refund",
                        verbose_name="Возврат в кассе",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на возврат",
                "verbose_name_plural": "Заявки на возврат",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="refundrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "processing"])),
                fields=("order",),
                name="uniq_open_refund_request_per_order",
            ),
        ),
    ]
