# Generated by Django 5.0.6 on 2026-07-15 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaxAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("max_user_id", models.BigIntegerField(unique=True, verbose_name="MAX user_id")),
                (
                    "chat_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="MAX chat_id"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон (норм.)")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="Фамилия")),
                (
                    "username",
                    models.CharField(blank=True, max_length=150, verbose_name="MAX username"),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Телефон подтверждён"),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True, verbose_name="Привязан")),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последний вход"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="max_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привязка MAX",
                "verbose_name_plural": "Привязки MAX",
            },
        ),
        migrations.CreateModel(
            name="MaxAuthAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="Публичный id"
                    ),
                ),
                ("secret_hash", models.CharField(max_length=64, verbose_name="Хэш секрета")),
                (
                    "browser_session_key",
                    models.CharField(max_length=64, verbose_name="Ключ браузер-сессии"),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("login", "Вход/регистрация"),
                            ("registration", "Регистрация"),
                            ("link", "Привязка MAX"),
                            ("confirm_login", "Подтверждение входа"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "max_user_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="MAX user_id"),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="MAX chat_id"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("confirmation_required", "Требует подтверждения"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("expired", "Истекла"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=64, verbose_name="Причина ошибки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершена в"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="max_auth_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка авторизации MAX",
                "verbose_name_plural": "Попытки авторизации MAX",
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"], name="integration_status_4be487_idx"
                    )
                ],
            },
        ),
    ]
