# Generated by Django 5.0.6 on 2026-07-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration_max", "0001_initial"),
        ("orders", "0009_alter_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="maxauthattempt",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="max_track_attempts",
                to="orders.order",
                verbose_name="Заказ (для track_order)",
            ),
        ),
        migrations.AlterField(
            model_name="maxauthattempt",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("login", "Вход/регистрация"),
                    ("registration", "Регистрация"),
                    ("link", "Привязка MAX"),
                    ("confirm_login", "Подтверждение входа"),
                    ("track_order", "Отслеживание гостевого заказа"),
                ],
                default="login",
                max_length=20,
                verbose_name="Тип операции",
            ),
        ),
        migrations.CreateModel(
            name="OrderTrackingGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("max_user_id", models.BigIntegerField(verbose_name="MAX user_id")),
                (
                    "chat_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="MAX chat_id"),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True, verbose_name="Выдан")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="max_tracking_grant",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Грант отслеживания заказа в MAX",
                "verbose_name_plural": "Гранты отслеживания заказа в MAX",
            },
        ),
    ]
