# Generated by Django 5.0.6 on 2026-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("enrich", "Обогащение"),
                            ("recommend", "Рекомендации"),
                            ("assist", "Ассистент"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("input_ref", models.CharField(blank=True, max_length=255)),
                ("output", models.JSONField(blank=True, null=True)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Успех"), ("fallback", "Фолбэк"), ("error", "Ошибка")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("entity_ref", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Вызов AI",
                "verbose_name_plural": "Журнал вызовов AI",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["capability", "status"], name="ai_aicalllo_capabil_8fb4bb_idx"
                    )
                ],
            },
        ),
    ]
