# Generated by Django 5.0.6 on 2026-06-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("catalog", "0023_sourcing_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("adapter", models.CharField(max_length=16)),
                ("provider", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("ok", "Ok"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("provider_idempotency_key", models.CharField(blank=True, max_length=128)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("reserved_cost", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("raw_excerpt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourcingBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("daily_cap", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("reserved", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("spent", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SourcingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("product_ref", models.PositiveIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("ok", "Ok"),
                            ("degraded", "Degraded"),
                            ("configuration_error", "Configuration Error"),
                            ("error", "Error"),
                        ],
                        default="running",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContentFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_ref", models.PositiveIntegerField(db_index=True)),
                ("target_kind", models.CharField(max_length=20)),
                ("attribute_slug", models.CharField(blank=True, default="", max_length=120)),
                ("value", models.JSONField()),
                ("normalized_hash", models.CharField(max_length=64)),
                ("source_name", models.CharField(max_length=16)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("last_outcome", models.CharField(blank=True, max_length=24)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FindingEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_name", models.CharField(max_length=16)),
                ("confidence", models.FloatField(default=0.0)),
                ("observed_value_hash", models.CharField(max_length=64)),
                ("observed_source", models.CharField(blank=True, max_length=16)),
                ("canonical_url", models.URLField(blank=True, max_length=500)),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ai.externalcall",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="ai.contentfinding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FindingApplicationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("claimed", "Claimed"), ("done", "Done"), ("failed", "Failed")],
                        default="claimed",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="ai.contentfinding",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ai.findingevidence",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentfinding",
            name="selected_evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ai.findingevidence",
            ),
        ),
        migrations.AddField(
            model_name="externalcall",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="ai.sourcingrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="findingevidence",
            constraint=models.UniqueConstraint(
                fields=("finding", "external_call", "canonical_url"), name="uniq_evidence"
            ),
        ),
        migrations.AddConstraint(
            model_name="findingapplicationattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "claimed")),
                fields=("finding",),
                name="uniq_active_claim_per_finding",
            ),
        ),
        migrations.AddIndex(
            model_name="contentfinding",
            index=models.Index(
                fields=["product_ref", "status"], name="ai_contentf_product_24c41b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentfinding",
            constraint=models.UniqueConstraint(
                fields=("product_ref", "target_kind", "attribute_slug", "normalized_hash"),
                name="uniq_finding_dedup",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentfinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("target_kind", "attribute"),
                        models.Q(("attribute_slug", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("target_kind", "attribute"), _negated=True),
                        ("attribute_slug", ""),
                    ),
                    _connector="OR",
                ),
                name="finding_attribute_slug_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalcall",
            constraint=models.UniqueConstraint(
                fields=("run", "adapter"), name="uniq_externalcall_run_adapter"
            ),
        ),
    ]
