# Generated by Django 5.0.6 on 2026-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_sourcing_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcall",
            name="reserved_day",
            field=models.DateField(blank=True, null=True),
        ),
    ]
