# Generated by Django 5.0.6 on 2026-07-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_externalcall_reserved_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentfinding",
            options={
                "verbose_name": "Находка по контенту",
                "verbose_name_plural": "Находки по контенту",
            },
        ),
        migrations.AlterModelOptions(
            name="externalcall",
            options={"verbose_name": "Внешний вызов", "verbose_name_plural": "Внешние вызовы"},
        ),
    ]
