# Generated by Django 5.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("search", "Поиск"),
                            ("product_view", "Просмотр товара"),
                            ("add_to_cart", "Добавление в корзину"),
                            ("checkout_start", "Начало оформления"),
                            ("order_created", "Заказ создан"),
                            ("payment_started", "Оплата начата"),
                            ("payment_success", "Оплата успешна"),
                            ("payment_fail", "Оплата не удалась"),
                        ],
                        max_length=30,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID сессии",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Данные события",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие аналитики",
                "verbose_name_plural": "События аналитики",
                "ordering": ["-created_at"],
            },
        ),
    ]
