# Generated by Django 5.0.6 on 2026-06-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("integer", "Целое число"),
                            ("decimal", "Число с точкой"),
                            ("boolean", "Да/Нет"),
                            ("select", "Список (одно значение)"),
                            ("multiselect", "Список (несколько значений)"),
                        ],
                        default="text",
                        max_length=12,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="Единица измерения"),
                ),
                (
                    "is_filterable",
                    models.BooleanField(default=False, verbose_name="Показывать в фильтре"),
                ),
                (
                    "is_comparable",
                    models.BooleanField(default=False, verbose_name="Показывать в сравнении"),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="Изображение"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Meta title"),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=512, verbose_name="Meta description"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="AttributeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalog.attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант характеристики",
                "verbose_name_plural": "Варианты характеристик",
                "ordering": ["sort_order", "value"],
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_1c",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Внутренний код номенклатуры 1С. Заполняется автоматически при синхронизации.",
                        max_length=50,
                        verbose_name="Код 1С",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Товарный артикул (SKU). Может совпадать с артикулом поставщика.",
                        max_length=100,
                        verbose_name="Артикул",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Название")),
                ("slug", models.SlugField(max_length=512, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=512, verbose_name="Краткое описание"),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Meta title"),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=512, verbose_name="Meta description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "attrs_cache",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Денормализованный JSON значений характеристик. Обновляется автоматически.",
                        verbose_name="Кэш характеристик",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/", verbose_name="Файл")),
                ("alt", models.CharField(blank=True, max_length=255, verbose_name="Alt-текст")),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное фото")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["-is_main", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_required", models.BooleanField(default=False, verbose_name="Обязательна")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="catalog.attribute",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика категории",
                "verbose_name_plural": "Характеристики категорий",
                "ordering": ["sort_order"],
                "unique_together": {("category", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_text", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "value_integer",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Целое"),
                ),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True, verbose_name="Число"
                    ),
                ),
                (
                    "value_boolean",
                    models.BooleanField(blank=True, null=True, verbose_name="Булево"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.attribute"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="catalog.product",
                    ),
                ),
                (
                    "value_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.attributeoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение характеристики",
                "verbose_name_plural": "Значения характеристик",
                "unique_together": {("product", "attribute")},
            },
        ),
    ]
