# Generated by Django 5.0.6 on 2026-06-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_quantity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Доступно"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=64, verbose_name="Штрихкод"),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name="Бренд"),
        ),
        migrations.AddField(
            model_name="product",
            name="category_is_manual",
            field=models.BooleanField(
                default=False,
                help_text="Если да — авторазбор её больше не меняет.",
                verbose_name="Категория назначена вручную",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="RUB", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active_1c",
            field=models.BooleanField(blank=True, null=True, verbose_name="Активен в 1С"),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Старая цена"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_name",
            field=models.CharField(
                blank=True,
                help_text="Исходное название из 1С. Обновляется импортом, на витрине не используется.",
                max_length=512,
                verbose_name="Название в 1С",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Цена обновлена"),
        ),
        migrations.AddField(
            model_name="product",
            name="reserved_quantity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Резерв"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="source_group",
            field=models.CharField(
                blank=True,
                help_text="Группа товара в 1С (справочно). Структуру сайта не определяет.",
                max_length=255,
                verbose_name="Исходная группа 1С",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("imported", "Импортирован (не разобран)"),
                    ("needs_review", "Требует проверки"),
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                ],
                db_index=True,
                default="imported",
                max_length=14,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Остаток"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "В наличии"),
                    ("out_of_stock", "Нет в наличии"),
                    ("on_order", "Под заказ"),
                ],
                default="out_of_stock",
                max_length=12,
                verbose_name="Наличие",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Остаток обновлён"),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(blank=True, max_length=32, verbose_name="Единица измерения"),
        ),
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="Артикул (SKU)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="attrs_cache",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Денормализованный JSON значений характеристик для фасетных фильтров.",
                verbose_name="Кэш характеристик",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто = «Неразобранные». Назначается правилом или вручную.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория сайта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code_1c",
            field=models.CharField(
                blank=True,
                help_text="Внутренний код/идентификатор номенклатуры 1С. Главный ключ связи.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Код 1С (external_id)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Виден на витрине только если статус «Опубликован» и этот флаг включён.",
                verbose_name="Показывать на сайте",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=512, verbose_name="Название (витрина)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=512, unique=True, verbose_name="Slug"),
        ),
        migrations.CreateModel(
            name="CategoryMappingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("article", "По артикулу (точное совпадение)"),
                            ("name_contains", "По слову в названии"),
                            ("brand_prefix", "По бренду + серии модели"),
                            ("source_group", "По исходной группе 1С"),
                        ],
                        max_length=20,
                        verbose_name="Тип правила",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Артикул / слово в названии / серия модели / название группы 1С — в зависимости от типа правила.",
                        max_length=255,
                        verbose_name="Образец",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Только для типа «бренд + серия»: например, Bosch.",
                        max_length=100,
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Меньше = раньше применяется.",
                        verbose_name="Приоритет",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_rules",
                        to="catalog.category",
                        verbose_name="Категория сайта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило сопоставления",
                "verbose_name_plural": "Правила сопоставления",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="matched_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_products",
                to="catalog.categorymappingrule",
                verbose_name="Сработавшее правило",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status", "category"], name="catalog_pro_status_9b3667_idx"),
        ),
    ]
