# Generated by Django 5.0.6 on 2026-06-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_available_quantity_product_barcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начат")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершён"),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Имя файла / команды запуска.",
                        max_length=255,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("done", "Завершён"),
                            ("failed", "Ошибка"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="categories_created, products_imported, tool_type_assigned, unmatched, recategorize_flagged, excluded.",
                        verbose_name="Счётчики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запуск импорта",
                "verbose_name_plural": "Запуски импорта",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="attributeoption",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="ЧПУ-идентификатор варианта (для SEO-фасетов вида ?tool_type=perforatory).",
                max_length=120,
                verbose_name="Slug",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="external_id_1c",
            field=models.CharField(
                blank=True,
                help_text="external_id группы 1С для листа дерева. Единственная связь категории с учётной системой (ADR-0002). Узлы-контейнеры остаются пустыми.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Код группы 1С",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="on_site",
            field=models.BooleanField(
                default=True,
                help_text="False — группа 1С не размещается на витрине (под скрытым корнем).",
                verbose_name="Показывать на сайте",
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="is_filter",
            field=models.BooleanField(
                default=True,
                help_text="Характеристика участвует в фасетных фильтрах этой категории.",
                verbose_name="Использовать в фильтре",
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="is_seo_facet",
            field=models.BooleanField(
                default=False,
                help_text="На основе значений строятся посадочные страницы (вторая ось навигации).",
                verbose_name="SEO-фасет",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="content_locked",
            field=models.BooleanField(
                default=False,
                help_text="Если включено — импорт из 1С не перезаписывает контентные поля (витринное название, описание, SEO). ADR: 1С не затирает ручную работу.",
                verbose_name="Контент защищён",
            ),
        ),
        migrations.CreateModel(
            name="EnrichmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_external_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="Код 1С товара"),
                ),
                ("raw_name", models.CharField(max_length=512, verbose_name="Название из 1С")),
                (
                    "category_path",
                    models.CharField(blank=True, max_length=512, verbose_name="Путь категории"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("assigned", "tool_type проставлен"),
                            ("moderation", "В очередь модерации"),
                            ("recategorize", "Сменить категорию"),
                        ],
                        db_index=True,
                        max_length=12,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(blank=True, max_length=255, verbose_name="tool_type"),
                ),
                (
                    "matched_keyword",
                    models.CharField(blank=True, max_length=255, verbose_name="Сработавшее слово"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_logs",
                        to="catalog.importrun",
                        verbose_name="Запуск",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог обогащения",
                "verbose_name_plural": "Логи обогащения",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["result", "tool_type"], name="catalog_enr_result_731a0e_idx"
                    )
                ],
            },
        ),
    ]
