# Generated by Django 5.0.6 on 2026-06-20 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_importrun_attributeoption_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_ai_feature",
            field=models.BooleanField(
                default=False,
                help_text="Плохо извлекается regex/словарём из названия — кандидат на добор LLM (#62).",
                verbose_name="AI-характеристика",
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="filter_kind",
            field=models.CharField(
                choices=[("select", "Список значений"), ("range", "Диапазон (min/max)")],
                default="select",
                help_text="range — числовой диапазон min/max (напряжение, момент); select — выбор из значений (тип питания, tool_type).",
                max_length=8,
                verbose_name="Вид фильтра",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="confidence",
            field=models.SmallIntegerField(
                default=100,
                help_text="0–100. regex=100, ключевое слово=90, AI задаёт 75/50.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Уверенность",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("name_regex", "Regex по названию"),
                    ("name_keyword", "Ключевое слово"),
                    ("llm", "AI / LLM"),
                ],
                default="manual",
                help_text="Приоритет перезаписи задаёт apps.catalog.source_priority.",
                max_length=12,
                verbose_name="Источник",
            ),
        ),
    ]
