# Generated by Django 5.0.6 on 2026-06-20 14:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_attribute_is_ai_feature_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["attrs_cache"], name="catalog_product_attrs_gin"
            ),
        ),
    ]
