# Generated by Django 5.0.6 on 2026-06-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_catalog_product_attrs_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("accessory", "Аксессуар / оснастка / расходник"),
                            ("compatible", "Совместим"),
                        ],
                        max_length=20,
                        verbose_name="Тип связи",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=512, verbose_name="Примечание")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compat_out",
                        to="catalog.product",
                        verbose_name="Товар-источник",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compat_in",
                        to="catalog.product",
                        verbose_name="Связанный товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь совместимости товаров",
                "verbose_name_plural": "Связи совместимости товаров",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["source", "kind"], name="catalog_pro_source__fad558_idx"),
                    models.Index(fields=["target", "kind"], name="catalog_pro_target__f77abe_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productcompatibility",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "kind"), name="catalog_productcompat_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcompatibility",
            constraint=models.CheckConstraint(
                check=models.Q(("source", models.F("target")), _negated=True),
                name="catalog_productcompat_no_self_link",
            ),
        ),
    ]
