# Generated by Django 5.0.6 on 2026-06-21 13:14

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productcompatibility_and_more"),
    ]

    operations = [
        # ВАЖНО: расширение pg_trgm должно создаваться ПЕРЕД индексами с
        # opclass gin_trgm_ops, иначе AddIndex упадёт (оператор недоступен).
        # TrigramExtension == CreateExtension("pg_trgm"); требует superuser.
        TrigramExtension(),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="catalog_product_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["article"], name="catalog_product_article_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["brand"], name="catalog_product_brand_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
