# Generated by Django 5.0.6 on 2026-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_catalog_product_name_trgm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattributevalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("regex", "Regex по названию"),
                    ("keyword", "Ключевое слово"),
                    ("llm", "AI/LLM"),
                    ("inferred", "Инференс по атрибутам"),
                ],
                default="manual",
                help_text="Приоритет перезаписи берётся из source_priority в attribute_rules.json: manual не затирается regex/keyword.",
                max_length=12,
                verbose_name="Источник",
            ),
        ),
    ]
