# Generated by Django 5.0.6 on 2026-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_productattributevalue_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryattribute",
            name="group",
            field=models.CharField(
                choices=[("main", "Основные"), ("extra", "Дополнительные")],
                default="main",
                help_text="Раздел в сайдбаре: «Основные» или «Дополнительные» (свёрнуты по умолчанию). Куратор переносит сюда второстепенные характеристики (вход — coverage-отчёт #225).",
                max_length=8,
                verbose_name="Группа фильтра",
            ),
        ),
    ]
