# Generated by Django 5.2.15 on 2026-06-26 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_merge_20260625_0530"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneCGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Код 1С (external_id)",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Имя группы 1С"),
                ),
                (
                    "site_path",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Путь на сайте (из маппинга)"
                    ),
                ),
                (
                    "product_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Товаров (по source_group)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна (есть товары)"),
                            ("stale", "Пустая (нет товаров)"),
                            ("discovered", "Найдена в выгрузке (нет в маппинге)"),
                        ],
                        db_index=True,
                        default="discovered",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "mapped_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onec_groups",
                        to="catalog.category",
                        verbose_name="Категория сайта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа 1С",
                "verbose_name_plural": "Группы 1С",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["status", "name"], name="catalog_one_status_ef0698_idx")
                ],
            },
        ),
    ]
