# Generated by Django 5.2.15 on 2026-06-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_onecgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCategoryMapping",
            fields=[],
            options={
                "verbose_name": "Сопоставление группы и категории",
                "verbose_name_plural": "Сопоставление групп и категорий",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.onecgroup",),
        ),
    ]
