# Generated by Django 5.2.15 on 2026-06-26 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_groupcategorymapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="onecgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="catalog.onecgroup",
                verbose_name="Родительская группа 1С",
            ),
        ),
    ]
