# Generated by Django 5.0.6 on 2026-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_groupcategorymapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="Видео (URL)"),
        ),
    ]
