# Generated by Django 5.2.15 on 2026-06-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_onecgroup_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteCategory",
            fields=[],
            options={
                "verbose_name": "Категория (сайт)",
                "verbose_name_plural": "Категории (сайт)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
    ]
