# Generated by Django 5.2.15 on 2026-06-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_sitecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_site_v2",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True — узел курируемого v2-дерева сайта (создан build_skeleton/build_section). Отличает витринное дерево от легаси-категорий, зеркалящих группы 1С. Раздел «Категории (сайт)» показывает только такие узлы.",
                verbose_name="Узел витрины v2",
            ),
        ),
    ]
