# Generated by Django 5.2.15 on 2026-06-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_category_is_site_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="onecgroup",
            name="tree_path",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Материализованный путь имён (для древовидной сортировки админки).",
                max_length=1024,
                verbose_name="Путь в дереве 1С",
            ),
        ),
    ]
