# Generated by Django 5.0.6 on 2026-06-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_onecgroup_tree_path_collation"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="hero_cta_href",
            field=models.CharField(blank=True, max_length=512, verbose_name="Hero: ссылка кнопки"),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_cta_label",
            field=models.CharField(blank=True, max_length=60, verbose_name="Hero: текст кнопки"),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_eyebrow",
            field=models.CharField(blank=True, max_length=120, verbose_name="Hero: слоган"),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_image",
            field=models.ImageField(
                blank=True, upload_to="categories/hero/", verbose_name="Hero: фон"
            ),
        ),
    ]
