# Generated by Django 5.0.6 on 2026-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_category_hero_cta_href_category_hero_cta_label_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteCategory",
        ),
        migrations.RemoveField(
            model_name="category",
            name="hero_cta_href",
        ),
        migrations.RemoveField(
            model_name="category",
            name="hero_cta_label",
        ),
        migrations.RemoveField(
            model_name="category",
            name="hero_eyebrow",
        ),
        migrations.RemoveField(
            model_name="category",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_site_v2",
        ),
        migrations.RemoveField(
            model_name="onecgroup",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="onecgroup",
            name="tree_path",
        ),
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="Видео (URL)"),
        ),
    ]
