# Generated by Django 5.0.6 on 2026-06-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_category_hero_cta_href_category_hero_cta_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content_confidence",
            field=models.FloatField(blank=True, null=True, verbose_name="Уверенность контента"),
        ),
        migrations.AddField(
            model_name="product",
            name="content_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("llm", "AI-генерация"),
                ],
                max_length=12,
                null=True,
                verbose_name="Источник карточного контента",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="enrich_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("in_queue", "В очереди"),
                    ("done", "Готово"),
                    ("moderation", "На модерации"),
                    ("failed", "Ошибка"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
                verbose_name="Статус обогащения",
            ),
        ),
    ]
