# Generated by Django 5.0.6 on 2026-06-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_product_enrich_fields"),
        ("catalog", "0019_product_video_url"),
    ]

    operations = []
