# Generated by Django 5.0.6 on 2026-06-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_merge_20260627_1138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("llm", "AI-генерация"),
                ],
                default="",
                max_length=12,
                verbose_name="Источник карточного контента",
            ),
        ),
    ]
