# Generated by Django 5.0.6 on 2026-06-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_alter_product_content_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationProduct",
            fields=[],
            options={
                "verbose_name": "Товар на модерации",
                "verbose_name_plural": "Очередь модерации обогащения",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
    ]
