# Generated by Django 5.0.6 on 2026-06-30 09:11

from django.db import migrations, models


def backfill_field_sources(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for p in Product.objects.exclude(content_source="").iterator():
        fields = {f: p.content_source for f in ("name", "short_description", "description")
                  if getattr(p, f)}
        if fields:
            p.content_field_sources = fields
            p.save(update_fields=["content_field_sources"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_moderationproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content_field_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{'name':'manual','description':'web'} — истинный источник по полю",
                verbose_name="Провенанс карточных полей",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="content_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("llm", "AI-генерация"),
                    ("web", "Web-поиск"),
                    ("marketplace", "Маркетплейс"),
                ],
                default="",
                max_length=12,
                verbose_name="Источник карточного контента",
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("regex", "Regex по названию"),
                    ("keyword", "Ключевое слово"),
                    ("llm", "AI/LLM"),
                    ("inferred", "Инференс по атрибутам"),
                    ("web", "Web-поиск"),
                    ("marketplace", "Маркетплейс"),
                ],
                default="manual",
                help_text="Приоритет перезаписи берётся из source_priority в attribute_rules.json: manual не затирается regex/keyword.",
                max_length=12,
                verbose_name="Источник",
            ),
        ),
        migrations.RunPython(backfill_field_sources, noop),
    ]
