# Generated by Django 5.0.6 on 2026-07-17 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_sourcing_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAvailabilitySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("max", "MAX")], default="max", max_length=10, verbose_name="Канал"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("queued", "В очереди на уведомление"),
                            ("notified", "Уведомлён"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Оформлена"),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Поставлена в очередь"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Уведомление отправлено"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Отменена"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_subscriptions",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на поступление",
                "verbose_name_plural": "Подписки на поступление",
                "indexes": [
                    models.Index(
                        fields=["product", "status"], name="catalog_pro_product_4bd832_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productavailabilitysubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user", "product", "channel"),
                name="uniq_active_availability_subscription",
            ),
        ),
    ]
