# Generated by Django 5.0.6 on 2026-07-17 13:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_productavailabilitysubscription_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogProcessingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Вручную"),
                            ("rules", "Правила"),
                            ("research", "Исследование"),
                            ("ai", "AI"),
                            ("import", "Импорт"),
                        ],
                        max_length=16,
                        verbose_name="Тип запуска",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("tool_type", "Тип инструмента")],
                        max_length=16,
                        verbose_name="Режим",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("running", "В работе"),
                            ("completed", "Завершён"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Ключ идемпотентности"
                    ),
                ),
                ("scope", models.JSONField(blank=True, default=dict, verbose_name="Скоуп")),
                (
                    "ruleset_version",
                    models.CharField(blank=True, max_length=64, verbose_name="Версия правил"),
                ),
                (
                    "ruleset_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="Хеш правил"),
                ),
                (
                    "taxonomy_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="Хеш таксономии"),
                ),
                ("stats", models.JSONField(blank=True, default=dict, verbose_name="Статистика")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершён"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запуск обработки каталога",
                "verbose_name_plural": "Запуски обработки каталога",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CatalogProcessingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_ref",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID товара для аудита"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "В обработке"),
                            ("needs_review", "Требует проверки"),
                            ("completed", "Завершён"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="Входной снапшот"),
                ),
                ("input_hash", models.CharField(max_length=64, verbose_name="Хеш входа")),
                (
                    "baseline_hashes",
                    models.JSONField(blank=True, default=dict, verbose_name="Базовые хеши"),
                ),
                (
                    "needed_targets",
                    models.JSONField(blank=True, default=list, verbose_name="Целевые поля"),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=32, verbose_name="Код ошибки"),
                ),
                (
                    "error_detail",
                    models.CharField(blank=True, max_length=255, verbose_name="Детали ошибки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершён"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.catalogprocessingrun",
                        verbose_name="Запуск",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент обработки",
                "verbose_name_plural": "Элементы обработки",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CatalogChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "product_ref",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID товара для аудита"
                    ),
                ),
                ("target_kind", models.CharField(max_length=32, verbose_name="Тип цели")),
                (
                    "target_key",
                    models.CharField(blank=True, max_length=64, verbose_name="Ключ цели"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Предложено"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("applied", "Применено"),
                            ("skipped", "Пропущено"),
                            ("conflict", "Конфликт"),
                            ("invalid", "Невалидно"),
                            ("failed", "Ошибка"),
                            ("reversed", "Отменено"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "before_value",
                    models.JSONField(blank=True, default=dict, verbose_name="Старое значение"),
                ),
                (
                    "proposed_value",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Предложенное значение"
                    ),
                ),
                (
                    "after_value",
                    models.JSONField(blank=True, default=dict, verbose_name="Итоговое значение"),
                ),
                (
                    "baseline_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="Базовый хеш"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Вручную"),
                            ("import_1c", "Импорт 1С"),
                            ("regex", "Regex по названию"),
                            ("keyword", "Ключевое слово"),
                            ("llm", "AI/LLM"),
                            ("inferred", "Инференс по атрибутам"),
                            ("web", "Web-поиск"),
                            ("marketplace", "Маркетплейс"),
                        ],
                        max_length=16,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "confidence",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Уверенность",
                    ),
                ),
                (
                    "rule_ref",
                    models.CharField(blank=True, max_length=64, verbose_name="Ссылка на правило"),
                ),
                (
                    "ruleset_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="Хеш набора правил"),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=32, verbose_name="Код причины"),
                ),
                (
                    "reason_detail",
                    models.CharField(blank=True, max_length=255, verbose_name="Детали причины"),
                ),
                (
                    "evidence",
                    models.JSONField(blank=True, default=dict, verbose_name="Доказательства"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время проверки"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время применения"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.catalogchange",
                        verbose_name="Отмена изменения",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="catalog.catalogprocessingitem",
                        verbose_name="Элемент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение каталога",
                "verbose_name_plural": "Изменения каталога",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product_ref", "target_kind", "created_at"],
                        name="catalog_cat_product_cf2f74_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="catalog_cat_status_c7e521_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="catalogchange",
            constraint=models.CheckConstraint(
                check=models.Q(("confidence__gte", 0), ("confidence__lte", 100)),
                name="catalog_change_confidence_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="catalogprocessingitem",
            unique_together={("run", "product_ref")},
        ),
    ]
