# Generated by Django 5.0.6 on 2026-07-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_catalogprocessingrun_catalogprocessingitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogchange",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Применил",
            ),
        ),
        migrations.AddField(
            model_name="catalogchange",
            name="comment",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Комментарий модератора"
            ),
        ),
        migrations.AlterField(
            model_name="catalogchange",
            name="after_value",
            field=models.JSONField(blank=True, null=True, verbose_name="Итоговое значение"),
        ),
        migrations.AlterField(
            model_name="catalogchange",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes",
                to="catalog.catalogprocessingitem",
                verbose_name="Элемент",
            ),
        ),
        migrations.AlterField(
            model_name="catalogchange",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("regex", "Regex по названию"),
                    ("keyword", "Ключевое слово"),
                    ("rules", "Правила каталога"),
                    ("llm", "AI/LLM"),
                    ("inferred", "Инференс по атрибутам"),
                    ("web", "Web-поиск"),
                    ("marketplace", "Маркетплейс"),
                ],
                max_length=16,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="catalogprocessingitem",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="catalog.catalogprocessingrun",
                verbose_name="Запуск",
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("regex", "Regex по названию"),
                    ("keyword", "Ключевое слово"),
                    ("rules", "Правила каталога"),
                    ("llm", "AI/LLM"),
                    ("inferred", "Инференс по атрибутам"),
                    ("web", "Web-поиск"),
                    ("marketplace", "Маркетплейс"),
                ],
                default="manual",
                help_text="Приоритет перезаписи берётся из source_priority в attribute_rules.json: manual не затирается regex/keyword.",
                max_length=12,
                verbose_name="Источник",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogchange",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(("reviewed_by__isnull", False), ("reviewed_at__isnull", False)),
                    _connector="OR",
                ),
                name="catalog_change_approved_requires_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogchange",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "rejected"), _negated=True),
                    models.Q(("reviewed_by__isnull", False), ("reviewed_at__isnull", False)),
                    _connector="OR",
                ),
                name="catalog_change_rejected_requires_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogchange",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "applied"), _negated=True),
                    models.Q(("after_value__isnull", False), ("applied_at__isnull", False)),
                    _connector="OR",
                ),
                name="catalog_change_applied_requires_after_value",
            ),
        ),
    ]
