# Generated by Django 5.0.6 on 2026-07-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_reslug_steplery_unique_option_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSalesStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="Продано за окно"
                    ),
                ),
                (
                    "days_with_sales",
                    models.PositiveIntegerField(default=0, verbose_name="Дней с продажами"),
                ),
                ("window_days", models.PositiveIntegerField(verbose_name="Окно, дней")),
                ("rank", models.PositiveIntegerField(verbose_name="Место в рейтинге")),
                (
                    "is_hit",
                    models.BooleanField(
                        default=False,
                        help_text="Топ рейтинга при достаточном числе продаж — источник бейджа «Хит».",
                        verbose_name="Хит продаж",
                    ),
                ),
                (
                    "last_sold_on",
                    models.DateField(blank=True, null=True, verbose_name="Последняя продажа"),
                ),
                ("computed_at", models.DateTimeField(auto_now=True, verbose_name="Пересчитан")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_stat",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг продаж товара",
                "verbose_name_plural": "Рейтинг продаж товаров",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="ProductSalesFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("site", "Заказы сайта"), ("1c", "Продажи 1С")],
                        max_length=8,
                        verbose_name="Источник",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата продажи")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Продано"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_facts",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажи товара за день",
                "verbose_name_plural": "Продажи товаров по дням",
                "indexes": [
                    models.Index(fields=["date", "product"], name="catalog_pro_date_aaa828_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productsalesfact",
            constraint=models.UniqueConstraint(
                fields=("product", "source", "date"), name="catalog_salesfact_unique_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsalesfact",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="catalog_salesfact_quantity_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="productsalesstat",
            index=models.Index(fields=["-quantity"], name="catalog_pro_quantit_d2ee14_idx"),
        ),
        migrations.AddIndex(
            model_name="productsalesstat",
            index=models.Index(fields=["is_hit", "rank"], name="catalog_pro_is_hit_2b5e34_idx"),
        ),
    ]
