# Generated by Django 5.0.6 on 2026-07-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_reslug_steplery_unique_option_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryattribute",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Переопределение названия характеристики для этой категории (глобальный Attribute может делиться между разными категориями). Пусто — используется название характеристики. Ключ фильтра (slug) не меняется.",
                max_length=255,
                verbose_name="Подпись в фильтре",
            ),
        ),
    ]
