# Generated by Django 5.0.6 on 2026-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_productsalesstat_productsalesfact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="card_name",
            field=models.CharField(
                blank=True,
                help_text="Короткая форма для плитки каталога. Пусто — показывается витринное название. Заполняет команда normalize_product_names.",
                max_length=512,
                verbose_name="Название (карточка)",
            ),
        ),
    ]
