# Generated by Django 5.0.6 on 2026-07-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_product_card_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория (все узлы, вкл. 1С)",
                "verbose_name_plural": "Категории: все узлы (вкл. 1С)",
            },
        ),
        migrations.AlterModelOptions(
            name="categorymappingrule",
            options={
                "ordering": ["priority", "id"],
                "verbose_name": "Правило автораскладки",
                "verbose_name_plural": "Автораскладка товаров по категориям",
            },
        ),
        migrations.AlterModelOptions(
            name="moderationproduct",
            options={
                "verbose_name": "Товар с AI-описанием",
                "verbose_name_plural": "Проверить AI-описания",
            },
        ),
        migrations.AlterModelOptions(
            name="sitecategory",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
    ]
