# Generated by Django 5.0.6 on 2026-07-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_productsalesstat_productsalesfact_and_more"),
        ("catalog", "0029_productattributevalue_source_scraper"),
    ]

    operations = []
