# Generated by Django 5.0.6 on 2026-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_merge_20260729_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogchange",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("import_1c", "Импорт 1С"),
                    ("regex", "Regex по названию"),
                    ("keyword", "Ключевое слово"),
                    ("rules", "Правила каталога"),
                    ("llm", "AI/LLM"),
                    ("inferred", "Инференс по атрибутам"),
                    ("web", "Web-поиск"),
                    ("marketplace", "Маркетплейс"),
                    ("scraper", "Парсер сайтов производителей"),
                ],
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
