# Generated by Django 5.0.6 on 2026-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_hit_manual",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Витринная подборка магазина, пока 1С не присылает продажи. Товары с реальными продажами за окно всё равно идут первыми — ручная отметка их не вытесняет и не подменяет (см. apps.catalog.sales).",
                verbose_name="Хит продаж (вручную)",
            ),
        ),
        migrations.AddField(
            model_name="productcompatibility",
            name="origin",
            field=models.CharField(
                choices=[("manual", "Менеджер"), ("ai", "Предложено ИИ")],
                default="manual",
                max_length=10,
                verbose_name="Источник связи",
            ),
        ),
        migrations.AlterField(
            model_name="productcompatibility",
            name="kind",
            field=models.CharField(
                choices=[
                    ("accessory", "Аксессуар / оснастка / расходник"),
                    ("compatible", "Совместим"),
                    ("cross_sell", "С этим товаром покупают"),
                    ("analog", "Аналог / замена"),
                ],
                max_length=20,
                verbose_name="Тип связи",
            ),
        ),
    ]
