# Generated by Django 5.0.6 on 2026-07-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_product_card_name"),
        ("catalog", "0031_alter_catalogchange_source"),
    ]

    operations = []
