# Generated by Django 5.0.6 on 2026-07-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_alter_category_options_and_more"),
        ("catalog", "0032_merge_20260729_2133"),
    ]

    operations = []
