# Generated by Django 5.0.6 on 2026-08-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_product_is_hit_manual_productcompatibility_origin_and_more"),
        ("catalog", "0033_merge_20260730_1821"),
    ]

    operations = []
