# Generated by Django 5.0.6 on 2026-08-07 18:29
"""ИЗО-02: провенанс изображений товара + идемпотентность повторного прогона.

Что делает:
- добавляет ``source``/``source_url``/``checksum``/``fetched_at`` в ProductImage;
- помечает ВСЕ уже существующие записи как ``manual`` (данные-миграция ниже) —
  откат прогона сбора обязан обходить их стороной;
- ставит два частичных unique-ограничения: ``(product, checksum)`` — основной
  ключ идемпотентности, ``(product, source_url)`` — дешёвая предпроверка.

Чего НЕ делает: ничего не удаляет и не трогает файлы в media. Миграция полностью
обратима: ``manage.py migrate catalog 0034_merge_gitlab_20260805`` снимает
ограничения и поля, существующие записи остаются на месте.
"""

from django.db import migrations, models


def stamp_existing_as_manual(apps, schema_editor):
    """Все записи, существовавшие до трека ИЗО, — загружены руками.

    AddField с default='manual' уже проставил бы это значение, но фиксируем
    намерение явно: строка с ``source='manual'`` — это гарантия, что откат
    прогона сбора её не увидит. Условие по ``fetched_at``/``source_url``
    делает шаг идемпотентным (повторный прогон ничего не переписывает).
    """
    ProductImage = apps.get_model("catalog", "ProductImage")
    ProductImage.objects.filter(fetched_at__isnull=True, source_url__isnull=True).update(
        source="manual"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_merge_gitlab_20260805"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="checksum",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="sha256 сохранённого файла: одна и та же картинка под разными URL.",
                max_length=64,
                null=True,
                verbose_name="Контрольная сумма",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="fetched_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Момент скачивания. Вместе с source задаёт границы отката прогона.",
                null=True,
                verbose_name="Получено",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Загружено вручную"),
                    ("resanta", "resanta.ru"),
                    ("vihr", "vihr.su"),
                    ("interskol", "interskol.ru"),
                    ("zubr", "zubr.ru"),
                ],
                db_index=True,
                default="manual",
                help_text="Откат прогона сбора удаляет только НЕ manual-записи.",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="source_url",
            field=models.URLField(
                blank=True,
                db_index=True,
                help_text="Абсолютный URL картинки на сайте производителя.",
                max_length=1000,
                null=True,
                verbose_name="URL источника",
            ),
        ),
        # Данные-миграция: обратный ход — no-op, поля всё равно снимаются выше.
        migrations.RunPython(stamp_existing_as_manual, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checksum__isnull", False)),
                fields=("product", "checksum"),
                name="uniq_product_image_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_url__isnull", False)),
                fields=("product", "source_url"),
                name="uniq_product_image_source_url",
            ),
        ),
    ]
