# Generated by Django 5.0.6 on 2026-08-12 08:53
#
# DRF-1003: запрет отрицательного available_quantity. Порядок операций важен —
# сначала чиним уже накопленные минусы, иначе AddConstraint не применится
# (на staging такие строки были).

import logging

import django.core.validators
from django.db import migrations, models

logger = logging.getLogger(__name__)


def clamp_negative_available(apps, schema_editor):
    """Зажать накопленные отрицательные остатки в ноль.

    Ноль — консервативный выбор: восстановить истинное значение неоткуда, а
    товар лучше временно не продавать, чем продать дважды. Ближайший обмен
    остатками с 1С перезапишет поле фактическим значением.
    """
    Product = apps.get_model("catalog", "Product")
    fixed = Product.objects.filter(available_quantity__lt=0).update(available_quantity=0)
    if fixed:
        logger.warning("DRF-1003: зажато в ноль отрицательных остатков: %s", fixed)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_productimage_provenance"),
    ]

    operations = [
        migrations.RunPython(clamp_negative_available, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="available_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Доступно",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("available_quantity__gte", 0)),
                name="catalog_product_available_qty_non_negative",
            ),
        ),
    ]
