# Generated by Django 5.0.6 on 2026-09-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0037_available_quantity_non_negative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Загружено вручную"),
                    ("resanta", "resanta.ru"),
                    ("vihr", "vihr.su"),
                    ("interskol", "interskol.ru"),
                    ("zubr", "zubr.ru"),
                    ("vseinstrumenti", "vseinstrumenti.ru"),
                ],
                db_index=True,
                default="manual",
                help_text="Откат прогона сбора удаляет только НЕ manual-записи.",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
