# Generated by Django 5.0.6 on 2026-09-04 07:23
# VI-INT-02: перенесена с 0038 на 0039 и поставлена поверх 0038_imagesource_huter —
# на staging 0038 уже занята миграцией huter (62 изображения source='huter').
# choices сохраняют ВСЕ существующие источники (включая huter) и только
# добавляют vseinstrumenti — существующие ImageSource/data не меняются.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0038_imagesource_huter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Загружено вручную"),
                    ("resanta", "resanta.ru"),
                    ("vihr", "vihr.su"),
                    ("interskol", "interskol.ru"),
                    ("zubr", "zubr.ru"),
                    ("huter", "huter.su"),
                    ("vseinstrumenti", "vseinstrumenti.ru"),
                ],
                db_index=True,
                default="manual",
                help_text="Откат прогона сбора удаляет только НЕ manual-записи.",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
