# Generated by Django 5.0.6 on 2026-09-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0039_image_source_vseinstrumenti"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["-is_main", "sort_order", "pk"],
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
            },
        ),
    ]
