# Generated by Django 5.0.6 on 2026-09-16 10:37

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0040_alter_productimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="display",
            field=models.ImageField(
                blank=True,
                help_text="Обработанная копия (белый фон, квадрат). Оригинал image не меняется.",
                upload_to=apps.catalog.models.product_image_display_path,
                verbose_name="Витринный файл",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="display_checksum",
            field=models.CharField(
                blank=True,
                default="",
                help_text="sha256 файла display; аудит сверяет его отдельно от checksum оригинала.",
                max_length=64,
                verbose_name="Контрольная сумма витринного файла",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Обработано"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="processing_mode",
            field=models.CharField(
                blank=True,
                choices=[("trim", "Обрезка полей"), ("rembg", "Удаление фона")],
                max_length=16,
                verbose_name="Способ обработки",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("none", "Не обрабатывалось"),
                    ("queued", "В очереди"),
                    ("needs_rembg", "Ждёт удаления фона"),
                    ("needs_review", "Ждёт проверки"),
                    ("done", "Обработано"),
                    ("rejected", "Оставлен оригинал"),
                    ("failed", "Ошибка обработки"),
                ],
                default="none",
                max_length=16,
                verbose_name="Обработка",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="processing_version",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Версия параметров, с которыми сделан display; 0 — не обрабатывалось.",
                verbose_name="Версия обработки",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="checksum",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="sha256 исходного файла image (не витринной копии): одна и та же картинка под разными URL.",
                max_length=64,
                null=True,
                verbose_name="Контрольная сумма",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["processing_status"], name="productimage_proc_status_idx"),
        ),
    ]
