# Generated by Django 5.0.6 on 2026-09-17 13:43
# MEDIA-SOURCE-01: реестр источников изображений + hanskonner / einhell / thorvik.
# Только choices (state Django): колонка — varchar(16) без CHECK/enum, SQL не
# выполняется, существующие значения и данные не меняются.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_productimage_display_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Загружено вручную"),
                    ("resanta", "resanta.ru"),
                    ("vihr", "vihr.su"),
                    ("interskol", "interskol.ru"),
                    ("zubr", "zubr.ru"),
                    ("huter", "huter.su"),
                    ("vseinstrumenti", "vseinstrumenti.ru"),
                    ("hanskonner", "hanskonner.ru"),
                    ("einhell", "einhell.de"),
                    ("thorvik", "thorvik.ru"),
                ],
                db_index=True,
                default="manual",
                help_text="Откат прогона сбора удаляет только НЕ manual-записи.",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
