# Generated by Django 5.0.6 on 2026-09-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_image_source_manufacturers"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Фото этого же товара, повтором которого оказался этот кадр.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.productimage",
                verbose_name="Дубль кадра",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Хэш изображения оригинала: по нему находятся одинаковые кадры товара.",
                max_length=64,
                verbose_name="Отпечаток кадра",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="review_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("duplicate", "Такой же кадр у товара уже есть"),
                    ("empty", "Товар на фото не найден"),
                    ("small", "Мелкое фото: товар меньше половины квадрата"),
                    ("not_white", "Фон был не белый — копию сделала нейросеть"),
                ],
                max_length=16,
                verbose_name="Почему на проверке",
            ),
        ),
    ]
