# Generated by Django 5.0.6 on 2026-09-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_productimage_quality_checks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("none", "Не обрабатывалось"),
                    ("queued", "В очереди"),
                    ("needs_rembg", "Ждёт удаления фона"),
                    ("needs_review", "Ждёт проверки"),
                    ("done", "Обработано"),
                    ("skipped", "Фон не трогаем: кадр не студийный"),
                    ("rejected", "Оставлен оригинал"),
                    ("failed", "Ошибка обработки"),
                ],
                default="none",
                max_length=16,
                verbose_name="Обработка",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="review_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("duplicate", "Такой же кадр у товара уже есть"),
                    ("empty", "Товар на фото не найден"),
                    ("small", "Мелкое фото: товар меньше половины квадрата"),
                    ("torn", "Нейросеть разорвала картинку на куски"),
                    ("not_white", "Фон был не белый — копию сделала нейросеть"),
                ],
                max_length=16,
                verbose_name="Почему на проверке",
            ),
        ),
    ]
