# Generated by Django 5.0.6 on 2026-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0045_image_source_dns"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="package_height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Габариты задаются тройкой: либо все три, либо ни одного.",
                null=True,
                verbose_name="Высота упаковки, см",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="package_length_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Длина упаковки, см"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="package_weight_g",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Пусто — берётся у раздела выше.",
                null=True,
                verbose_name="Вес в упаковке, г",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="package_width_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ширина упаковки, см"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Габариты задаются тройкой: либо все три, либо ни одного.",
                null=True,
                verbose_name="Высота упаковки, см",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_length_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Длина упаковки, см"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_weight_g",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Пусто — берётся у раздела выше.",
                null=True,
                verbose_name="Вес в упаковке, г",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_width_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ширина упаковки, см"
            ),
        ),
    ]
