# Generated by Django 5.0.6 on 2026-09-24 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_package_dimensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image_ref", models.PositiveBigIntegerField(verbose_name="ID фото")),
                ("product_ref", models.PositiveBigIntegerField(verbose_name="ID товара")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("qc_decision", "Решение контролёра"),
                            ("accept_candidate", "Кандидат принят"),
                            ("reject_candidate", "Кандидат отклонён"),
                            ("return_to_review", "Возвращён на проверку из архива"),
                            ("revert_original", "Оригинал закреплён"),
                            ("reprocess", "Отправлен на переобработку"),
                            ("set_purpose", "Изменено назначение кадра"),
                            ("set_main_fit", "Изменена пригодность главным"),
                            ("set_main", "Назначено главным фото"),
                            ("manual_rembg_requested", "Запрошено ручное удаление фона"),
                            ("source_replacement", "Отмечена нужда в замене исходника"),
                        ],
                        max_length=32,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Автоматика"),
                            ("human", "Человек"),
                            ("legacy", "Унаследовано без контролёра"),
                        ],
                        max_length=8,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "render_key",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Ключ отрисовки"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Контрольная сумма"
                    ),
                ),
                ("before", models.JSONField(blank=True, default=dict, verbose_name="До")),
                ("after", models.JSONField(blank=True, default=dict, verbose_name="После")),
                ("reasons", models.JSONField(blank=True, default=list, verbose_name="Причины")),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Заметка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
            ],
            options={
                "verbose_name": "Событие по фото",
                "verbose_name_plural": "События по фото",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="RejectedImageCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image_ref", models.PositiveBigIntegerField(verbose_name="ID фото")),
                ("product_ref", models.PositiveBigIntegerField(verbose_name="ID товара")),
                (
                    "product_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Снимок товара и исходника"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=apps.catalog.models.private_media_storage,
                        upload_to=apps.catalog.models.rejected_candidate_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Контрольная сумма"
                    ),
                ),
                (
                    "readable",
                    models.BooleanField(
                        default=True,
                        help_text="False — показывать ссылку, а не превью.",
                        verbose_name="Файл читается",
                    ),
                ),
                (
                    "render_key",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Ключ отрисовки"
                    ),
                ),
                (
                    "processing_version",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Версия обработки"),
                ),
                (
                    "qc_rules_version",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Версия правил контролёра"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("trim", "Обрезка полей"), ("rembg", "Удаление фона")],
                        max_length=16,
                        verbose_name="Способ отрисовки",
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list, verbose_name="Причины")),
                (
                    "reason_text",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Причина"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Автоматика"),
                            ("human", "Человек"),
                            ("legacy", "Унаследовано без контролёра"),
                        ],
                        default="auto",
                        max_length=8,
                        verbose_name="Источник решения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("rejected", "Отклонён"), ("returned", "Возвращён на проверку")],
                        default="rejected",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
            ],
            options={
                "verbose_name": "Отклонённое фото",
                "verbose_name_plural": "Отклонённые фото",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="productimage",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Попыток обработки"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="candidate",
            field=models.ImageField(
                blank=True,
                help_text="Свежий результат обработки, ждущий решения. На витрину не идёт.",
                upload_to=apps.catalog.models.product_image_display_path,
                verbose_name="Файл-кандидат",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="candidate_checksum",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Контрольная сумма кандидата"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="candidate_created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Кандидат создан"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="candidate_mode",
            field=models.CharField(
                blank=True,
                choices=[("trim", "Обрезка полей"), ("rembg", "Удаление фона")],
                max_length=16,
                verbose_name="Способ отрисовки кандидата",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="candidate_render_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="sha256(исходник + версия параметров + маршрут). Тот же ключ — тот же результат: повторная задача не рисует файл и не зовёт nейросеть заново.",
                max_length=64,
                verbose_name="Ключ отрисовки кандидата",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="display_render_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ключ отрисовки, которым сделан текущий display — для отката и аудита.",
                max_length=64,
                verbose_name="Ключ отрисовки принятой копии",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="last_error",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Последняя ошибка"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="main_fit_auto",
            field=models.CharField(
                choices=[
                    ("unchecked", "Не проверено"),
                    ("suitable", "Подходит"),
                    ("unsuitable", "Не подходит"),
                ],
                default="unchecked",
                max_length=16,
                verbose_name="Пригодность главным (авто)",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="main_fit_human",
            field=models.CharField(
                choices=[
                    ("unchecked", "Не проверено"),
                    ("suitable", "Подходит"),
                    ("unsuitable", "Не подходит"),
                ],
                default="unchecked",
                help_text="Подтверждение человеком — приоритетнее автоматического предположения.",
                max_length=16,
                verbose_name="Пригодность главным (человек)",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="main_fit_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Причина по пригодности"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="manual_rembg_requested",
            field=models.BooleanField(
                default=False,
                help_text="«Предметное фото: подготовить удаление фона» — точечное действие человека для сложного НЕ чёрного фона; авто-правило `other → rembg` не расширяет.",
                verbose_name="Запрошено ручное удаление фона",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="needs_source_replacement",
            field=models.BooleanField(default=False, verbose_name="Нужна замена исходника"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("unknown", "Неизвестно"),
                    ("whole", "Товар целиком"),
                    ("detail", "Деталь товара"),
                    ("kit", "Комплектация / кейс"),
                    ("promo", "Рекламный кадр"),
                    ("in_use", "Фото в работе"),
                ],
                default="unknown",
                max_length=16,
                verbose_name="Назначение кадра",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="qc_decided_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Решение принято"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="qc_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto_accept", "Принять автоматически"),
                    ("auto_reject_candidate", "Отклонить кандидата"),
                    ("needs_review", "Нужна проверка человеком"),
                ],
                max_length=24,
                verbose_name="Решение контролёра",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="qc_features",
            field=models.JSONField(blank=True, default=dict, verbose_name="Измеренные признаки"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="qc_reasons",
            field=models.JSONField(blank=True, default=list, verbose_name="Причины решения"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="qc_rules_version",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Версия правил контролёра"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="qc_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "Автоматика"),
                    ("human", "Человек"),
                    ("legacy", "Унаследовано без контролёра"),
                ],
                max_length=8,
                verbose_name="Кто решил",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="revision",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Растёт при каждом решении человека. Воркер, начавший обработку при меньшей ревизии, не перезаписывает более новое решение (устаревший результат отбрасывается, статус `stale`).",
                verbose_name="Ревизия решения",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="source_replacement_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Почему нужна замена"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("none", "Не обрабатывалось"),
                    ("queued", "В очереди"),
                    ("needs_rembg", "Ждёт удаления фона"),
                    ("needs_review", "Ждёт проверки"),
                    ("done", "Обработано"),
                    ("skipped", "Фон не трогаем: кадр не студийный"),
                    ("rejected", "Оставлен оригинал"),
                    ("failed", "Ошибка обработки"),
                    ("observed", "Готово, ждёт включения маршрута"),
                    ("candidate_rejected", "Кандидат отклонён"),
                ],
                default="none",
                max_length=24,
                verbose_name="Обработка",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["purpose"], name="productimage_purpose_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["qc_decision"], name="productimage_qc_decision_idx"),
        ),
        migrations.AddField(
            model_name="productimageevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто",
            ),
        ),
        migrations.AddField(
            model_name="productimageevent",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="catalog.productimage",
                verbose_name="Фото",
            ),
        ),
        migrations.AddField(
            model_name="rejectedimagecandidate",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто отклонил",
            ),
        ),
        migrations.AddField(
            model_name="rejectedimagecandidate",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_candidates",
                to="catalog.productimage",
                verbose_name="Фото",
            ),
        ),
        migrations.AddIndex(
            model_name="productimageevent",
            index=models.Index(fields=["image_ref"], name="imgevent_image_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="productimageevent",
            index=models.Index(fields=["product_ref"], name="imgevent_product_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="rejectedimagecandidate",
            index=models.Index(fields=["product_ref"], name="rejcand_product_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="rejectedimagecandidate",
            index=models.Index(fields=["status"], name="rejcand_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="rejectedimagecandidate",
            constraint=models.UniqueConstraint(
                fields=("image_ref", "render_key", "checksum"),
                name="uniq_rejected_candidate_render",
            ),
        ),
    ]
