# Generated by Django 5.0.6 on 2026-07-01 19:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Имя автора"),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("product", "Товар"), ("order", "Заказ")],
                        db_index=True,
                        default="product",
                        max_length=20,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "subject_id",
                    models.PositiveIntegerField(db_index=True, verbose_name="ID объекта"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Текст отзыва")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На модерации"),
                            ("approved", "Одобрен"),
                            ("rejected", "Отклонён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата модерации"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject_type", "subject_id", "status"],
                        name="reviews_subject_status_idx",
                    )
                ],
            },
        ),
    ]
