# Generated by Django 5.0.6 on 2026-06-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Полная выгрузка"),
                            ("prices", "Цены"),
                            ("stock", "Остатки"),
                            ("orders", "Заказы"),
                        ],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("ok", "Успешно"), ("partial", "Частично"), ("error", "Ошибка")],
                        max_length=10,
                        verbose_name="Результат",
                    ),
                ),
                ("rows_total", models.PositiveIntegerField(default=0, verbose_name="Всего строк")),
                ("rows_ok", models.PositiveIntegerField(default=0, verbose_name="Обработано")),
                ("rows_error", models.PositiveIntegerField(default=0, verbose_name="Ошибок")),
                ("error_details", models.TextField(blank=True, verbose_name="Детали ошибок")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начало")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Конец")),
            ],
            options={
                "verbose_name": "Лог синхронизации",
                "verbose_name_plural": "Логи синхронизации",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="NomenclatureStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_1c", models.CharField(db_index=True, max_length=50, verbose_name="Код 1С")),
                (
                    "article",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Артикул"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Все поля строки/узла из выгрузки 1С в исходном виде.",
                        verbose_name="Исходные данные",
                    ),
                ),
                (
                    "name_1c",
                    models.CharField(blank=True, max_length=512, verbose_name="Название в 1С"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="Единица измерения"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Цена (из выгрузки)",
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="Остаток (из выгрузки)",
                    ),
                ),
                (
                    "is_active_1c",
                    models.BooleanField(
                        blank=True,
                        help_text="None = поле не найдено в выгрузке.",
                        null=True,
                        verbose_name="Активен в 1С",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("matched", "Привязан к товару"),
                            ("new", "Новый товар (не привязан)"),
                            ("error", "Ошибка парсинга"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Сообщение об ошибке")),
                (
                    "imported_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время импорта"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время обработки"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_records",
                        to="catalog.product",
                        verbose_name="Товар каталога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись выгрузки 1С",
                "verbose_name_plural": "Записи выгрузки 1С",
                "ordering": ["-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "imported_at"], name="sync_1c_nom_status_5b95f3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_1c", models.CharField(db_index=True, max_length=50, verbose_name="Код 1С")),
                (
                    "price_type",
                    models.CharField(
                        default="retail",
                        help_text="retail / wholesale / promo или код типа цены из 1С.",
                        max_length=50,
                        verbose_name="Тип цены",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Цена"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "is_current",
                    models.BooleanField(db_index=True, default=True, verbose_name="Актуальная"),
                ),
                ("valid_from", models.DateTimeField(auto_now_add=True, verbose_name="Действует с")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_records",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена из 1С",
                "verbose_name_plural": "Цены из 1С",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["code_1c", "price_type", "is_current"],
                        name="sync_1c_pri_code_1c_5afecb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_1c", models.CharField(db_index=True, max_length=50, verbose_name="Код 1С")),
                (
                    "warehouse",
                    models.CharField(
                        default="main",
                        help_text="Код или название склада из 1С.",
                        max_length=100,
                        verbose_name="Склад",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, max_digits=14, verbose_name="Количество"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_records",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток из 1С",
                "verbose_name_plural": "Остатки из 1С",
                "indexes": [
                    models.Index(
                        fields=["code_1c", "warehouse"], name="sync_1c_sto_code_1c_8cb339_idx"
                    )
                ],
                "unique_together": {("code_1c", "warehouse")},
            },
        ),
    ]
