# Generated by Django 5.0.6 on 2026-06-13 15:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_1c", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclaturestaging",
            name="raw_payload",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Все поля строки/узла из выгрузки 1С в исходном виде.",
                verbose_name="Исходные данные",
            ),
        ),
    ]
