# Generated by Django 5.0.6 on 2026-06-13 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_available_quantity_product_barcode_and_more"),
        ("sync_1c", "0002_alter_nomenclaturestaging_raw_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclaturestaging",
            name="row_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 от raw_payload — для выявления повторных строк.",
                max_length=64,
                verbose_name="Хэш строки",
            ),
        ),
        migrations.AddField(
            model_name="nomenclaturestaging",
            name="source_file",
            field=models.CharField(blank=True, max_length=255, verbose_name="Файл-источник"),
        ),
        migrations.AddField(
            model_name="nomenclaturestaging",
            name="sync_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to="sync_1c.synclog",
                verbose_name="Прогон импорта",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="batch_uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UID прогона"
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="source_file",
            field=models.CharField(
                blank=True,
                help_text="Имя файла/период выгрузки.",
                max_length=255,
                verbose_name="Файл-источник",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("code_1c", "price_type", "currency"),
                name="uniq_current_price_per_code_type_currency",
            ),
        ),
    ]
