# Generated by Django 5.0.6 on 2026-06-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_1c", "0003_nomenclaturestaging_row_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclaturestaging",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает обработки"),
                    ("matched", "Привязан к товару"),
                    ("new", "Новый товар (не привязан)"),
                    ("skipped", "Пропущен (нет товара для обновления)"),
                    ("error", "Ошибка парсинга"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
