# Generated by Django 5.0.6 on 2026-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_1c", "0006_remove_pricerecord_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclog",
            name="external_batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Trace-id из 1С (если передан). Только для аудита — не используется при matching.",
                max_length=100,
                verbose_name="Внешний ID партии",
            ),
        ),
    ]
