# Generated by Django 5.0.6 on 2026-07-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_1c", "0007_add_external_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclog",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("full", "Полная выгрузка"),
                    ("prices", "Цены"),
                    ("stock", "Остатки"),
                    ("orders", "Заказы"),
                    ("sales", "Продажи"),
                ],
                max_length=10,
                verbose_name="Тип",
            ),
        ),
    ]
