# Generated by Django 5.0.6 on 2026-06-20 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("max", "MAX мессенджер"), ("email", "E-mail")],
                        max_length=10,
                        verbose_name="Канал",
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=100, verbose_name="Событие")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                            ("skipped", "Пропущено"),
                        ],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог уведомления",
                "verbose_name_plural": "Лог уведомлений",
                "ordering": ["-created_at"],
            },
        ),
    ]
