# Generated by Django 5.0.6 on 2026-07-02 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="chat_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="MAX chat ID"),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="provider_message_id",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="ID сообщения у провайдера"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст сообщения"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "В очереди"),
                    ("sending", "Отправляется"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка"),
                    ("skipped", "Пропущено"),
                    ("unknown", "Статус неизвестен"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uniq_notification_idempotency_key",
            ),
        ),
    ]
