# Generated by Django 5.0.6 on 2026-07-17 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationlog_chat_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_enabled",
                    models.BooleanField(default=True, verbose_name="Канал MAX включён"),
                ),
                (
                    "order_updates_enabled",
                    models.BooleanField(default=True, verbose_name="Статусы заказов"),
                ),
                (
                    "product_availability_enabled",
                    models.BooleanField(default=True, verbose_name="Появление товара"),
                ),
                (
                    "marketing_enabled",
                    models.BooleanField(default=False, verbose_name="Маркетинговые рассылки"),
                ),
                (
                    "marketing_consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Согласие на маркетинг"
                    ),
                ),
                (
                    "marketing_consent_version",
                    models.CharField(blank=True, max_length=32, verbose_name="Версия согласия"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.CharField(db_index=True, max_length=100, verbose_name="Событие")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account", "Аккаунт"),
                            ("order_updates", "Статусы заказов"),
                            ("product_availability", "Появление товара"),
                            ("marketing", "Маркетинг"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Категория",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="Данные")),
                (
                    "template_version",
                    models.PositiveIntegerField(default=1, verbose_name="Версия шаблона"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                (
                    "policy_skip_reason",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Причина пропуска по preferences"
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="Прочитано")),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification",
                        to="notifications.notificationlog",
                        verbose_name="Доставка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "read_at"], name="notificatio_user_id_47e85c_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uniq_notification_intent_idempotency_key",
            ),
        ),
    ]
