# Generated by Django 5.0.6 on 2026-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_usernotificationpreference_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="error_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("retryable", "Временная (можно повторить)"),
                    ("permanent", "Постоянная (повтор бессмыслен)"),
                ],
                help_text="Заполняется только при status=failed — retryable/permanent (#521).",
                max_length=10,
                verbose_name="Тип ошибки",
            ),
        ),
    ]
