# Generated by Django 5.0.6 on 2026-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationlog_error_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="recipients",
            field=models.TextField(
                blank=True,
                help_text="Адреса через запятую (e-mail-канал).",
                verbose_name="Получатели",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="subject",
            field=models.CharField(blank=True, max_length=255, verbose_name="Тема письма"),
        ),
    ]
